### ISSUE TITLE
Wrong dependency to PHPUnit in production code

### ISSUE THREAD

**Issue by cherifGsoul** [celyes/ray#1]
Line https://github.com/celyes/ray/blob/946a91b4057723632d6e813771bc1ec7368b9143/src/Ray.php#L8

I think it is an unintentional mistake to depend on PHPUnit exception while PHPUnit doesn't even exist in the dependency list.
The fix would be to use PHP exception: `use Exception` or a custom exception class.

**Comment by celyes** [comment]
Thank you for your comment @cherifGsoul . You're absolutely right. This was unintentional. I literally wrote this entire library this morning 😅 so I didn't have enough time to add any CS fixers or measures to detect this type of issue. I'll fix it asap. Thank you again!

**Comment by celyes** [comment]
fixed. check https://github.com/celyes/ray/pull/3
